### PR TITLE
bump peerDeps for vite 5

### LINKED ISSUE #89: Add support for vite 5.0
Vite 5.0 is out but this package is only compatible with vite up to 4.x

### PR DESCRIPTION
**Pull request by JoviDeCroock**
I tested this on Prefresh already, I have yet to fully test it with this project. I figured that creating the PR is already good to find typing issues.

Resolves #89

### CODE REVIEW

**Review by rschristian — APPROVED** [review]
Hah, was actually just on my way to do this too

Do we want to bump the Vite devDep though? Makes it a bit more difficult to ensure we're actually supporting anything less than v5

**Comment by JoviDeCroock** [comment]
@rschristian I did get a very odd warning when upgrading which seemed related to our other older deps so no issue doing the downgrade 😅

**Comment by JoviDeCroock** [comment]
First warning I encounter when trying it out

> The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

**Comment by rschristian** [comment]
Looks like they might've also missed some Rollup type defs when inlining them in the newest version, so that failed our CI too.

**Pull request merged**
