### PR TITLE
feat: jsxInject override

### PR DESCRIPTION
**Pull request by commenthol**
Some tooling (outside vite/ esbuild) require the `import {h} from 'preact'` being explicitely set in code as the injection is not known to those.
This causes constant pain when needing to switch same jsx code to a different bundling tool.
In this change a `jsxInject` override plugin property is introduced to allow custom overriding of the jsxInject method.
Most probably you'd like to use it this way in your `vite.config.ts` file
```
import { defineConfig } from "vite";
import preact from "@preact/preset-vite";

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [preact({ jsxInject: '' })],
});
```

### CODE REVIEW

**Comment by darklight9811** [comment]
Could anyone take a look at this? This is preventing me from using tsup to bundle a preact library (since vite does not support exporting types, at least not correctly with preact). And I would rather not reimplement this plugin inside vite, and since this could help other programmers, I think it should be implemented soon.

cc @marvinhagemeister

**Comment by marvinhagemeister** [comment]
I'm not sure if the path chosen in this PR is a good way forward. It resolves the described issue at the expense of more cognitive complexity for new users to Preact.

Picture a person new to frontend development that tries out Preact with this vite preset. The changes to the README in this PR tell them to always set `jsxInject` to an empty string. At this stage they'll likely struggle with the concept of JSX in general and the changes in this PR tell them to immediately learn about `jsxInject` which doesn't seem beginner friendly to me.

The proper solution would be to go a similar route like the react preset. Since prefresh requires a babel pass anyway we should do the JSX transpilation there. That would also allow the newer `jsx-runtime` transpilation to be used. The one in `esbuild` relies on the classic `createElement` call instead. That would drop the need for exposing `jsxInject` and resolve #4 .

**Comment by bdombro** [comment]
@darklight9811 have you tried the latest Vite preact-ts template? Looks like they added type support at somepoint so that TS files are aware that h and Fragment are available without explicit import.

Another potential workaround is to use my npmjs.com/patch-package patch I posted at https://github.com/preactjs/preset-vite/issues/24

@marvinhagemeister you make some good points, but I feel like this PR may be good even if we go with your proposed solution, bc it may be helpful to customize jsxInject for potentially other profits. Seeing as how the new feature is so cheap from a code perspective, maybe allow it for now? And then maybe consider reversing if and when we can support the jsx-runtime approach?

**Comment by commenthol** [comment]
Hi @marvinhagemeister,
Thanks for the feedback. I am sorry that I can't follow on the mentioned tech details on newer runtimes and things that may be part of the future. To be honest I would like to use things now, but I also understand that the new option shall not be subject to confusion. Therefore I tried to solve things by hopefully better explaining in the updated README.
Maybe this could serve as a compromise for the moment?

**Pull request closed without merging**
